package sali.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import sali.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.22 16:07:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TulosTest {



  // Generated by ComTest BEGIN
  /** testGetTulos33 */
  @Test
  public void testGetTulos33() {    // Tulos: 33
    Tulos t = new Tulos(); 
    t.setTulos("1"); 
    assertEquals("From: Tulos line: 36", 1, t.getTulos()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLisatiedot47 */
  @Test
  public void testGetLisatiedot47() {    // Tulos: 47
    Tulos t = new Tulos(); 
    t.setLisatieto("kg"); 
    assertEquals("From: Tulos line: 50", "kg", t.getLisatiedot()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTaytaTuloksella76 */
  @Test
  public void testTaytaTuloksella76() {    // Tulos: 76
    Tulos t = new Tulos(); 
    t.taytaTuloksella(1, 1); 
    assertEquals("From: Tulos line: 79", 1, t.getSuorittajaId()); 
    assertEquals("From: Tulos line: 80", 1, t.getLiikeId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTulosId92 */
  @Test
  public void testGetTulosId92() {    // Tulos: 92
    Tulos t = new Tulos(); 
    t.setTulosId(1); 
    assertEquals("From: Tulos line: 95", 1, t.getTulosId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetSuorittajaId106 */
  @Test
  public void testGetSuorittajaId106() {    // Tulos: 106
    Tulos t = new Tulos(); 
    t.taytaTuloksella(1, 1); 
    assertEquals("From: Tulos line: 109", 1, t.getSuorittajaId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLiikeId120 */
  @Test
  public void testGetLiikeId120() {    // Tulos: 120
    Tulos t = new Tulos(); 
    t.taytaTuloksella(1, 1); 
    assertEquals("From: Tulos line: 123", 1, t.getLiikeId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPvm134 */
  @Test
  public void testGetPvm134() {    // Tulos: 134
    Tulos t = new Tulos(); 
    t.setPvm("1991-09-29"); 
    assertEquals("From: Tulos line: 137", "1991-09-29", t.getPvm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi157 */
  @Test
  public void testRekisteroi157() {    // Tulos: 157
    Tulos t1 = new Tulos(); 
    assertEquals("From: Tulos line: 159", 0, t1.getTulosId()); 
    t1.rekisteroi(); 
    Tulos t2 = new Tulos(); 
    t2.rekisteroi(); 
    int n1 = t1.getTulosId(); 
    int n2 = t2.getTulosId(); 
    assertEquals("From: Tulos line: 165", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString199 */
  @Test
  public void testToString199() {    // Tulos: 199
    Tulos t = new Tulos(); 
    t.parse("1|1|1"); 
    assertEquals("From: Tulos line: 202", true, t.toString().startsWith("1|1|1|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse220 */
  @Test
  public void testParse220() {    // Tulos: 220
    Tulos t = new Tulos(); 
    t.parse("1|1|1"); 
    assertEquals("From: Tulos line: 223", 1, t.getTulosId()); 
    assertEquals("From: Tulos line: 224", true, t.toString().startsWith("1|1|1|")); 
    t.rekisteroi(); 
    int n = t.getTulosId(); 
    t.parse(""+(n+20)); 
    t.rekisteroi(); 
    assertEquals("From: Tulos line: 229", n+20+1, t.getTulosId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone257 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone257() throws CloneNotSupportedException {    // Tulos: 257
    Tulos t = new Tulos(); 
    t.parse("1|1|1"); 
    Tulos kopio = t.clone(); 
    assertEquals("From: Tulos line: 262", t.toString(), kopio.toString()); 
    t.parse("2|2|2"); 
    assertEquals("From: Tulos line: 264", false, kopio.toString().equals(t.toString())); 
  } // Generated by ComTest END
}